using Avalonia;
using Avalonia.Controls;
using Avalonia.Input;
using Avalonia.Interactivity;
using Avalonia.Media;
using Nodify.Events;
using Nodify.Interactivity;
using System;

namespace Nodify;

/// <summary>
/// The container for all the items generated by the <see cref="ItemsControl.ItemsSource"/> of the <see cref="NodifyEditor"/>.
/// </summary>
/// <remarks>
/// This is a functional implementation supporting location tracking, selection, and connector integration.
/// Advanced features like dragging will be added when the full Interactivity system is ported.
/// </remarks>
public class ItemContainer : ContentControl, INodifyCanvasItem
{
    #region Styled Properties

    public static readonly StyledProperty<IBrush?> HighlightBrushProperty =
        AvaloniaProperty.Register<ItemContainer, IBrush?>(nameof(HighlightBrush));

    public static readonly StyledProperty<IBrush?> SelectedBrushProperty =
        AvaloniaProperty.Register<ItemContainer, IBrush?>(nameof(SelectedBrush));

    public static readonly StyledProperty<Thickness> SelectedBorderThicknessProperty =
        AvaloniaProperty.Register<ItemContainer, Thickness>(nameof(SelectedBorderThickness), defaultValue: new Thickness(2));

    public static readonly StyledProperty<bool> IsSelectableProperty =
        AvaloniaProperty.Register<ItemContainer, bool>(nameof(IsSelectable), defaultValue: true);

    public static readonly StyledProperty<bool> IsSelectedProperty =
        AvaloniaProperty.Register<ItemContainer, bool>(
            nameof(IsSelected),
            defaultValue: false,
            defaultBindingMode: Avalonia.Data.BindingMode.TwoWay);

    private static readonly DirectProperty<ItemContainer, bool?> IsPreviewingSelectionPropertyKey =
        AvaloniaProperty.RegisterDirect<ItemContainer, bool?>(
            nameof(IsPreviewingSelection),
            o => o.IsPreviewingSelection,
            (o, v) => o.IsPreviewingSelection = v);

    public static readonly StyledProperty<Point> LocationProperty =
        AvaloniaProperty.Register<ItemContainer, Point>(
            nameof(Location),
            defaultValue: default(Point),
            defaultBindingMode: Avalonia.Data.BindingMode.TwoWay);

    public static readonly StyledProperty<Size> ActualSizeProperty =
        AvaloniaProperty.Register<ItemContainer, Size>(nameof(ActualSize), defaultValue: default(Size));

    public static readonly StyledProperty<Size?> DesiredSizeForSelectionProperty =
        AvaloniaProperty.Register<ItemContainer, Size?>(nameof(DesiredSizeForSelection));

    private static readonly DirectProperty<ItemContainer, bool> IsPreviewingLocationPropertyKey =
        AvaloniaProperty.RegisterDirect<ItemContainer, bool>(
            nameof(IsPreviewingLocation),
            o => o.IsPreviewingLocation,
            (o, v) => o.IsPreviewingLocation = v);

    public static readonly StyledProperty<bool> IsDraggableProperty =
        AvaloniaProperty.Register<ItemContainer, bool>(nameof(IsDraggable), defaultValue: true);

    // TODO: Replace with AddOwner when NodifyEditor.HasCustomContextMenuProperty is implemented
    public static readonly StyledProperty<bool> HasCustomContextMenuProperty =
        AvaloniaProperty.Register<ItemContainer, bool>(nameof(HasCustomContextMenu), defaultValue: false);

    /// <summary>
    /// Gets or sets the brush used when the <see cref="PendingConnection.IsOverElementProperty"/> attached property is true for this <see cref="ItemContainer"/>.
    /// </summary>
    public IBrush? HighlightBrush
    {
        get => GetValue(HighlightBrushProperty);
        set => SetValue(HighlightBrushProperty, value);
    }

    /// <summary>
    /// Gets or sets the brush used when <see cref="IsSelected"/> or <see cref="IsPreviewingSelection"/> is true.
    /// </summary>
    public IBrush? SelectedBrush
    {
        get => GetValue(SelectedBrushProperty);
        set => SetValue(SelectedBrushProperty, value);
    }

    /// <summary>
    /// Gets or sets the border thickness used when <see cref="IsSelected"/> or <see cref="IsPreviewingSelection"/> is true.
    /// </summary>
    public Thickness SelectedBorderThickness
    {
        get => GetValue(SelectedBorderThicknessProperty);
        set => SetValue(SelectedBorderThicknessProperty, value);
    }

    /// <summary>
    /// Gets or sets the location of this <see cref="ItemContainer"/> inside the <see cref="NodifyEditor"/> in graph space coordinates.
    /// </summary>
    public Point Location
    {
        get => GetValue(LocationProperty);
        set => SetValue(LocationProperty, value);
    }

    /// <summary>
    /// Gets or sets a value that indicates whether this <see cref="ItemContainer"/> is selected.
    /// Can only be set if <see cref="IsSelectable"/> is true.
    /// </summary>
    public bool IsSelected
    {
        get => GetValue(IsSelectedProperty);
        set => SetValue(IsSelectedProperty, value);
    }

    private bool? _isPreviewingSelection;
    /// <summary>
    /// Gets a value indicating whether this <see cref="ItemContainer"/> is about to change its <see cref="IsSelected"/> state.
    /// </summary>
    public bool? IsPreviewingSelection
    {
        get => _isPreviewingSelection;
        internal set => SetAndRaise(IsPreviewingSelectionPropertyKey, ref _isPreviewingSelection, value);
    }

    /// <summary>
    /// Gets or sets whether this <see cref="ItemContainer"/> can be selected.
    /// </summary>
    public bool IsSelectable
    {
        get => GetValue(IsSelectableProperty);
        set => SetValue(IsSelectableProperty, value);
    }

    private bool _isPreviewingLocation;
    /// <summary>
    /// Gets a value indicating whether this <see cref="ItemContainer"/> is previewing a new location but didn't logically move there.
    /// </summary>
    public bool IsPreviewingLocation
    {
        get => _isPreviewingLocation;
        protected internal set => SetAndRaise(IsPreviewingLocationPropertyKey, ref _isPreviewingLocation, value);
    }

    /// <summary>
    /// Gets the actual size of this <see cref="ItemContainer"/>.
    /// </summary>
    public Size ActualSize
    {
        get => GetValue(ActualSizeProperty);
        set => SetValue(ActualSizeProperty, value);
    }

    /// <summary>
    /// Overrides the size to check against when calculating if this <see cref="ItemContainer"/> can be part of the current selection area.
    /// Defaults to <see cref="Bounds"/>.Size.
    /// </summary>
    public Size? DesiredSizeForSelection
    {
        get => GetValue(DesiredSizeForSelectionProperty);
        set => SetValue(DesiredSizeForSelectionProperty, value);
    }

    /// <summary>
    /// Gets or sets whether this <see cref="ItemContainer"/> can be dragged.
    /// </summary>
    public bool IsDraggable
    {
        get => GetValue(IsDraggableProperty);
        set => SetValue(IsDraggableProperty, value);
    }

    /// <summary>
    /// Gets or sets a value indicating whether the container uses a custom context menu.
    /// </summary>
    /// <remarks>When set to true, the container handles the right-click event for specific interactions.</remarks>
    public bool HasCustomContextMenu
    {
        get => GetValue(HasCustomContextMenuProperty);
        set => SetValue(HasCustomContextMenuProperty, value);
    }

    /// <summary>
    /// Gets a value indicating whether the container has a context menu.
    /// </summary>
    public bool HasContextMenu => ContextMenu != null || HasCustomContextMenu;

    #endregion

    #region Routed Events

    public static readonly RoutedEvent<RoutedEventArgs> SelectedEvent =
        RoutedEvent.Register<ItemContainer, RoutedEventArgs>(nameof(Selected), RoutingStrategies.Bubble);

    public static readonly RoutedEvent<RoutedEventArgs> UnselectedEvent =
        RoutedEvent.Register<ItemContainer, RoutedEventArgs>(nameof(Unselected), RoutingStrategies.Bubble);

    public static readonly RoutedEvent<RoutedEventArgs> LocationChangedEvent =
        RoutedEvent.Register<ItemContainer, RoutedEventArgs>(nameof(LocationChanged), RoutingStrategies.Bubble);

    /// <summary>
    /// Occurs when the <see cref="Location"/> of this <see cref="ItemContainer"/> is changed.
    /// </summary>
    public event EventHandler<RoutedEventArgs> LocationChanged
    {
        add => AddHandler(LocationChangedEvent, value);
        remove => RemoveHandler(LocationChangedEvent, value);
    }

    /// <summary>
    /// Occurs when this <see cref="ItemContainer"/> is selected.
    /// </summary>
    public event EventHandler<RoutedEventArgs> Selected
    {
        add => AddHandler(SelectedEvent, value);
        remove => RemoveHandler(SelectedEvent, value);
    }

    /// <summary>
    /// Occurs when this <see cref="ItemContainer"/> is unselected.
    /// </summary>
    public event EventHandler<RoutedEventArgs> Unselected
    {
        add => AddHandler(UnselectedEvent, value);
        remove => RemoveHandler(UnselectedEvent, value);
    }

    #endregion

    #region Fields and Events

    /// <summary>
    /// Indicates whether right-click on the container should preserve the current selection.
    /// </summary>
    /// <remarks>Has no effect if the container has a context menu.</remarks>
    public static bool PreserveSelectionOnRightClick { get; set; }

    /// <summary>
    /// The <see cref="NodifyEditor"/> that owns this <see cref="ItemContainer"/>.
    /// </summary>
    public NodifyEditor? Editor { get; internal set; }

    /// <summary>
    /// The calculated margin when the container is selected or previewing selection.
    /// </summary>
    public Thickness SelectedMargin => new Thickness(
        BorderThickness.Left - SelectedBorderThickness.Left,
        BorderThickness.Top - SelectedBorderThickness.Top,
        BorderThickness.Right - SelectedBorderThickness.Right,
        BorderThickness.Bottom - SelectedBorderThickness.Bottom);

    /// <summary>
    /// Occurs when this <see cref="ItemContainer"/> is previewing a new <see cref="Location"/>.
    /// </summary>
    public event PreviewLocationChanged? PreviewLocationChanged;

    #endregion

    static ItemContainer()
    {
        LocationProperty.Changed.AddClassHandler<ItemContainer>((item, e) => item.OnLocationPropertyChanged(e));
        IsSelectedProperty.Changed.AddClassHandler<ItemContainer>((item, e) => item.OnIsSelectedPropertyChanged(e));
        FocusableProperty.OverrideDefaultValue<ItemContainer>(true);
    }

    /// <summary>
    /// Constructs an instance of an <see cref="ItemContainer"/> in the specified <see cref="NodifyEditor"/>.
    /// </summary>
    /// <param name="editor">The editor that owns this container.</param>
    public ItemContainer(NodifyEditor editor)
    {
        Editor = editor;

        // Track size changes
        PropertyChanged += OnPropertyChanged;

        // Setup input handling via the Interactivity system
        InputProcessor.AddSharedHandlers(this);
    }

    private void OnPropertyChanged(object? sender, AvaloniaPropertyChangedEventArgs e)
    {
        if (e.Property == BoundsProperty)
        {
            ActualSize = Bounds.Size;
        }
    }

    private void OnLocationPropertyChanged(AvaloniaPropertyChangedEventArgs e)
    {
        OnLocationChanged();

        if (Editor != null && Editor.IsLoaded && !Editor.IsBulkUpdatingItems)
        {
            Editor.ItemsHost?.InvalidateArrange();
        }
    }

    private void OnIsSelectedPropertyChanged(AvaloniaPropertyChangedEventArgs e)
    {
        bool newValue = IsSelectable && (bool)e.NewValue!;
        if (newValue != (bool)e.NewValue!)
        {
            IsSelected = newValue;
        }
        OnSelectedChanged(newValue);
    }

    /// <summary>
    /// Raises the <see cref="LocationChangedEvent"/> and sets <see cref="IsPreviewingLocation"/> to false.
    /// </summary>
    protected void OnLocationChanged()
    {
        IsPreviewingLocation = false;
        RaiseEvent(new RoutedEventArgs(LocationChangedEvent, this));
    }

    /// <summary>
    /// Raises the <see cref="PreviewLocationChanged"/> event and sets <see cref="IsPreviewingLocation"/> to true.
    /// </summary>
    /// <param name="newLocation">The new preview location.</param>
    protected internal void OnPreviewLocationChanged(Point newLocation)
    {
        IsPreviewingLocation = true;
        PreviewLocationChanged?.Invoke(newLocation);
    }

    /// <summary>
    /// Raises the <see cref="SelectedEvent"/> or <see cref="UnselectedEvent"/> based on <paramref name="newValue"/>.
    /// Called when the <see cref="IsSelected"/> value is changed.
    /// </summary>
    /// <param name="newValue">True if selected, false otherwise.</param>
    protected void OnSelectedChanged(bool newValue)
    {
        // Don't raise the event if the editor is selecting
        if (Editor != null && !Editor.IsSelecting)
        {
            RaiseEvent(new RoutedEventArgs(newValue ? SelectedEvent : UnselectedEvent, this));
        }
    }

    #region Selection Methods

    /// <summary>
    /// Selects this container based on the specified selection type.
    /// </summary>
    /// <param name="type">The type of selection operation.</param>
    public void Select(SelectionType type)
    {
        switch (type)
        {
            case SelectionType.Replace:
                // TODO: Implement when full NodifyEditor selection is available
                IsSelected = true;
                break;

            case SelectionType.Append:
                IsSelected = true;
                break;

            case SelectionType.Remove:
                IsSelected = false;
                break;

            case SelectionType.Invert:
                IsSelected = !IsSelected;
                break;
        }
    }

    /// <summary>
    /// Tests if a point within the container bounds is selectable.
    /// </summary>
    /// <param name="point">The point to test in container coordinates.</param>
    /// <returns>True if the point is within selectable bounds.</returns>
    public bool IsSelectableLocation(Point point)
    {
        var bounds = GetBounds();
        return bounds.Contains(point);
    }

    /// <summary>
    /// Tests if this container is selectable within the specified area.
    /// </summary>
    /// <param name="area">The area to test against.</param>
    /// <param name="fit">If true, the container must be fully contained; otherwise, only intersecting is required.</param>
    /// <returns>True if the container is selectable in the area.</returns>
    public bool IsSelectableInArea(Rect area, bool fit)
    {
        var bounds = GetBounds();
        return fit ? area.Contains(bounds) : area.Intersects(bounds);
    }

    /// <summary>
    /// Gets the bounds of this container in graph space.
    /// </summary>
    public Rect GetBounds()
    {
        Size size = DesiredSizeForSelection ?? Bounds.Size;
        return new Rect(Location, size);
    }

    #endregion

    #region INodifyCanvasItem Implementation

    Size INodifyCanvasItem.DesiredSize => DesiredSize;

    void INodifyCanvasItem.Arrange(Rect rect)
    {
        Arrange(rect);
    }

    #endregion

    #region Dragging Methods (Stubs for future implementation)

    /// <summary>
    /// Begins a dragging operation.
    /// </summary>
    /// <remarks>Full implementation requires the Interactivity system.</remarks>
    public void BeginDragging()
    {
        // TODO: Implement when Interactivity system is ported
        // For now, ensure the container is selected
        if (!IsSelected && IsSelectable)
        {
            Select(SelectionType.Replace);
        }
    }

    /// <summary>
    /// Updates the dragging operation.
    /// </summary>
    /// <param name="offset">The offset to apply.</param>
    /// <remarks>Full implementation requires the Interactivity system.</remarks>
    public void UpdateDragging(Vector offset)
    {
        // TODO: Implement when Interactivity system is ported
    }

    /// <summary>
    /// Cancels the dragging operation.
    /// </summary>
    /// <remarks>Full implementation requires the Interactivity system.</remarks>
    public void CancelDragging()
    {
        // TODO: Implement when Interactivity system is ported
    }

    /// <summary>
    /// Ends the dragging operation.
    /// </summary>
    /// <remarks>Full implementation requires the Interactivity system.</remarks>
    public void EndDragging()
    {
        // TODO: Implement when Interactivity system is ported
    }

    #endregion

    #region Input Processing

    protected InputProcessor InputProcessor { get; } = new InputProcessor();

    /// <inheritdoc />
    protected override void OnPointerPressed(PointerPressedEventArgs e)
    {
        base.OnPointerPressed(e);
        InputProcessor.ProcessEvent(e);
    }

    /// <inheritdoc />
    protected override void OnPointerReleased(PointerReleasedEventArgs e)
    {
        base.OnPointerReleased(e);
        InputProcessor.ProcessEvent(e);

        // Release the pointer capture if all buttons are released and there's no interaction in progress
        if (!InputProcessor.RequiresInputCapture && e.Pointer.Captured == this)
        {
            var props = e.GetCurrentPoint(this).Properties;
            if (!props.IsLeftButtonPressed && !props.IsRightButtonPressed && !props.IsMiddleButtonPressed)
            {
                e.Pointer.Capture(null);
            }
        }
    }

    /// <inheritdoc />
    protected override void OnPointerMoved(PointerEventArgs e)
    {
        base.OnPointerMoved(e);
        InputProcessor.ProcessEvent(e);
    }

    /// <inheritdoc />
    protected override void OnPointerWheelChanged(PointerWheelEventArgs e)
    {
        base.OnPointerWheelChanged(e);
        InputProcessor.ProcessEvent(e);
    }

    /// <inheritdoc />
    protected override void OnPointerCaptureLost(PointerCaptureLostEventArgs e)
    {
        base.OnPointerCaptureLost(e);
        InputProcessor.ProcessEvent(e);
    }

    /// <inheritdoc />
    protected override void OnKeyUp(KeyEventArgs e)
    {
        base.OnKeyUp(e);
        InputProcessor.ProcessEvent(e);
    }

    /// <inheritdoc />
    protected override void OnKeyDown(KeyEventArgs e)
    {
        base.OnKeyDown(e);
        InputProcessor.ProcessEvent(e);
    }

    #endregion
}
